name: Async DockerHub Image

on:
  workflow_dispatch:
    inputs:
      guacd_version:
        description: 'guacd version'
        required: true
        default: '1.5.3-bullseye'
      guacenc_version:
        description: 'guacenc version'
        required: true
        default: '1.5.3-bullseye'
      openjdk_version:
        description: 'openjdk version'
        required: true
        default: '17-slim-bullseye'
      maven_version:
        description: 'maven version'
        required: true
        default: '3.9.5-openjdk-17-slim-bullseye'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to FIT2CLOUD Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.fit2cloud.com
          username: ${{ secrets.FIT2CLOUD_USERNAME }}
          password: ${{ secrets.FIT2CLOUD_TOKEN }}
      
      - name: Set crane
        run: |
          tag=$(curl -s https://api.github.com/repos/google/go-containerregistry/releases/latest | jq -r '.tag_name')
          curl -fsL https://github.com/google/go-containerregistry/releases/download/${tag}/go-containerregistry_Linux_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin crane

      - name: Push guacd image
        run: |
          crane cp docker.io/jumpserver/guacd:${{ github.event.inputs.guacd_version }} registry.fit2cloud.com/jumpserver/guacd:${{ github.event.inputs.guacd_version }}
      
      - name: Push guacenc image
        run: |
          crane cp docker.io/jumpserver/guacenc:${{ github.event.inputs.guacenc_version }} registry.fit2cloud.com/jumpserver/guacenc:${{ github.event.inputs.guacenc_version }}
      
      - name: Push openjdk image
        run: |
          crane cp docker.io/jumpserver/openjdk:${{ github.event.inputs.openjdk_version }} registry.fit2cloud.com/jumpserver/openjdk:${{ github.event.inputs.openjdk_version }}

      - name: Push maven image
        run: |
          crane cp docker.io/jumpserver/maven:${{ github.event.inputs.maven_version }} registry.fit2cloud.com/jumpserver/maven:${{ github.event.inputs.maven_version }}